//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Spc.Ofp.Tubs.DAL {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FieldNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FieldNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Spc.Ofp.Tubs.DAL.FieldNames", typeof(FieldNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternate Name.
        /// </summary>
        public static string AlternateName {
            get {
                return ResourceManager.GetString("AlternateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Other Auxilary Boats.
        /// </summary>
        public static string AuxiliaryBoatCount {
            get {
                return ResourceManager.GetString("AuxiliaryBoatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beacon.
        /// </summary>
        public static string Beacon {
            get {
                return ResourceManager.GetString("Beacon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bearing.
        /// </summary>
        public static string Bearing {
            get {
                return ResourceManager.GetString("Bearing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity of Brail 1.
        /// </summary>
        public static string Brail1Size {
            get {
                return ResourceManager.GetString("Brail1Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity of Brail 2.
        /// </summary>
        public static string Brail2Size {
            get {
                return ResourceManager.GetString("Brail2Size", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brailing End Time.
        /// </summary>
        public static string BrailEndTime {
            get {
                return ResourceManager.GetString("BrailEndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brail Number.
        /// </summary>
        public static string BrailNumber {
            get {
                return ResourceManager.GetString("BrailNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brailing Start Time.
        /// </summary>
        public static string BrailStartTime {
            get {
                return ResourceManager.GetString("BrailStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brailing Type Description.
        /// </summary>
        public static string BrailType {
            get {
                return ResourceManager.GetString("BrailType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capacity.
        /// </summary>
        public static string Capacity {
            get {
                return ResourceManager.GetString("Capacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain.
        /// </summary>
        public static string Captain {
            get {
                return ResourceManager.GetString("Captain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Captain&apos;s Nationality.
        /// </summary>
        public static string CaptainCountryCode {
            get {
                return ResourceManager.GetString("CaptainCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Closed Date.
        /// </summary>
        public static string ClosedDate {
            get {
                return ResourceManager.GetString("ClosedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Code.
        /// </summary>
        public static string ConditionCode {
            get {
                return ResourceManager.GetString("ConditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condition Description.
        /// </summary>
        public static string ConditionDescription {
            get {
                return ResourceManager.GetString("ConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country Code.
        /// </summary>
        public static string CountryCode {
            get {
                return ResourceManager.GetString("CountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cruise Speed.
        /// </summary>
        public static string CruiseSpeed {
            get {
                return ResourceManager.GetString("CruiseSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCT Notes.
        /// </summary>
        public static string DctNotes {
            get {
                return ResourceManager.GetString("DctNotes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DCT Confidence Score.
        /// </summary>
        public static string DctScore {
            get {
                return ResourceManager.GetString("DctScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date.
        /// </summary>
        public static string DepartureDate {
            get {
                return ResourceManager.GetString("DepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detection Method.
        /// </summary>
        public static string DetectionMethod {
            get {
                return ResourceManager.GetString("DetectionMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance.
        /// </summary>
        public static string Distance {
            get {
                return ResourceManager.GetString("Distance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EEZ Identifier.
        /// </summary>
        public static string EezId {
            get {
                return ResourceManager.GetString("EezId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engine Power.
        /// </summary>
        public static string EnginePower {
            get {
                return ResourceManager.GetString("EnginePower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Units.
        /// </summary>
        public static string EnginePowerUnits {
            get {
                return ResourceManager.GetString("EnginePowerUnits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered By.
        /// </summary>
        public static string EnteredBy {
            get {
                return ResourceManager.GetString("EnteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entered Date.
        /// </summary>
        public static string EnteredDate {
            get {
                return ResourceManager.GetString("EnteredDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FADs (No School).
        /// </summary>
        public static string FadsNoSchool {
            get {
                return ResourceManager.GetString("FadsNoSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FADs (With School).
        /// </summary>
        public static string FadsWithSchool {
            get {
                return ResourceManager.GetString("FadsWithSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Master.
        /// </summary>
        public static string FishingMaster {
            get {
                return ResourceManager.GetString("FishingMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fish Per Brail.
        /// </summary>
        public static string FishPerBrail {
            get {
                return ResourceManager.GetString("FishPerBrail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Objects (No School).
        /// </summary>
        public static string FloatingObjectsNoSchool {
            get {
                return ResourceManager.GetString("FloatingObjectsNoSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Floating Objects (With School).
        /// </summary>
        public static string FloatingObjectsWithSchool {
            get {
                return ResourceManager.GetString("FloatingObjectsWithSchool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Count.
        /// </summary>
        public static string FormCount {
            get {
                return ResourceManager.GetString("FormCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Form Name.
        /// </summary>
        public static string FormName {
            get {
                return ResourceManager.GetString("FormName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Free Schools.
        /// </summary>
        public static string FreeSchools {
            get {
                return ResourceManager.GetString("FreeSchools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of full (1) brails.
        /// </summary>
        public static string FullBrailCount {
            get {
                return ResourceManager.GetString("FullBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GEN-3 Event Observed?.
        /// </summary>
        public static string Gen3Events {
            get {
                return ResourceManager.GetString("Gen3Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gross Tonnage.
        /// </summary>
        public static string GrossTonnage {
            get {
                return ResourceManager.GetString("GrossTonnage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Other Tender Boats Work With Catcher?.
        /// </summary>
        public static string HasTenderBoats {
            get {
                return ResourceManager.GetString("HasTenderBoats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter Color.
        /// </summary>
        public static string HelicopterColor {
            get {
                return ResourceManager.GetString("HelicopterColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter Make.
        /// </summary>
        public static string HelicopterMake {
            get {
                return ResourceManager.GetString("HelicopterMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter Model.
        /// </summary>
        public static string HelicopterModel {
            get {
                return ResourceManager.GetString("HelicopterModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter Range.
        /// </summary>
        public static string HelicopterRange {
            get {
                return ResourceManager.GetString("HelicopterRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helicopter Registration Number.
        /// </summary>
        public static string HelicopterRegistration {
            get {
                return ResourceManager.GetString("HelicopterRegistration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count of other vessels serviced by this helicopter.
        /// </summary>
        public static string HelicopterServiceOtherCount {
            get {
                return ResourceManager.GetString("HelicopterServiceOtherCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Host Vessel Action Code.
        /// </summary>
        public static string HostActionCode {
            get {
                return ResourceManager.GetString("HostActionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspection Date.
        /// </summary>
        public static string InspectionDate {
            get {
                return ResourceManager.GetString("InspectionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IRCS.
        /// </summary>
        public static string Ircs {
            get {
                return ResourceManager.GetString("Ircs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed Condition Code.
        /// </summary>
        public static string LandedConditionCode {
            get {
                return ResourceManager.GetString("LandedConditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landed Condition Description.
        /// </summary>
        public static string LandedConditionDescription {
            get {
                return ResourceManager.GetString("LandedConditionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onboard Handling Description.
        /// </summary>
        public static string LandedHandling {
            get {
                return ResourceManager.GetString("LandedHandling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude.
        /// </summary>
        public static string Latitude {
            get {
                return ResourceManager.GetString("Latitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length.
        /// </summary>
        public static string Length {
            get {
                return ResourceManager.GetString("Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Length Code.
        /// </summary>
        public static string LengthCode {
            get {
                return ResourceManager.GetString("LengthCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Licenses.
        /// </summary>
        public static string Licenses {
            get {
                return ResourceManager.GetString("Licenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Availability.
        /// </summary>
        public static string LifejacketAvailability {
            get {
                return ResourceManager.GetString("LifejacketAvailability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provided For Observer.
        /// </summary>
        public static string LifejacketProvided {
            get {
                return ResourceManager.GetString("LifejacketProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suitable Size.
        /// </summary>
        public static string LifejacketSizeOk {
            get {
                return ResourceManager.GetString("LifejacketSizeOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ship&apos;s Time.
        /// </summary>
        public static string LocalTime {
            get {
                return ResourceManager.GetString("LocalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude.
        /// </summary>
        public static string Longitude {
            get {
                return ResourceManager.GetString("Longitude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Make.
        /// </summary>
        public static string Make {
            get {
                return ResourceManager.GetString("Make", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fishing Master&apos;s Nationality.
        /// </summary>
        public static string MasterCountryCode {
            get {
                return ResourceManager.GetString("MasterCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Material.
        /// </summary>
        public static string Material {
            get {
                return ResourceManager.GetString("Material", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measuring Instrument.
        /// </summary>
        public static string MeasuringInstrument {
            get {
                return ResourceManager.GetString("MeasuringInstrument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mesh Size.
        /// </summary>
        public static string MeshSize {
            get {
                return ResourceManager.GetString("MeshSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Model.
        /// </summary>
        public static string Model {
            get {
                return ResourceManager.GetString("Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Net Strips.
        /// </summary>
        public static string NetStrips {
            get {
                return ResourceManager.GetString("NetStrips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 1/8 (8) brails.
        /// </summary>
        public static string OneEighthBrailCount {
            get {
                return ResourceManager.GetString("OneEighthBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 1/2 (5) brails.
        /// </summary>
        public static string OneHalfBrailCount {
            get {
                return ResourceManager.GetString("OneHalfBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 1/4 (7) brails.
        /// </summary>
        public static string OneQuarterBrailCount {
            get {
                return ResourceManager.GetString("OneQuarterBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 1/3 (6) brails.
        /// </summary>
        public static string OneThirdBrailCount {
            get {
                return ResourceManager.GetString("OneThirdBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Number.
        /// </summary>
        public static string PageNumber {
            get {
                return ResourceManager.GetString("PageNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo Number.
        /// </summary>
        public static string PhotoNumber {
            get {
                return ResourceManager.GetString("PhotoNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Pollution.
        /// </summary>
        public static string PollutionType {
            get {
                return ResourceManager.GetString("PollutionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Code.
        /// </summary>
        public static string PortCode {
            get {
                return ResourceManager.GetString("PortCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Port Name.
        /// </summary>
        public static string PortName {
            get {
                return ResourceManager.GetString("PortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power.
        /// </summary>
        public static string Power {
            get {
                return ResourceManager.GetString("Power", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observer Program Code.
        /// </summary>
        public static string ProgramCode {
            get {
                return ResourceManager.GetString("ProgramCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Code.
        /// </summary>
        public static string ProjectCode {
            get {
                return ResourceManager.GetString("ProjectCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quantity.
        /// </summary>
        public static string Quantity {
            get {
                return ResourceManager.GetString("Quantity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered Country Code.
        /// </summary>
        public static string RegisteredCountryCode {
            get {
                return ResourceManager.GetString("RegisteredCountryCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Number.
        /// </summary>
        public static string RegistrationNumber {
            get {
                return ResourceManager.GetString("RegistrationNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Date.
        /// </summary>
        public static string ReturnDate {
            get {
                return ResourceManager.GetString("ReturnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Association.
        /// </summary>
        public static string SchoolAssociation {
            get {
                return ResourceManager.GetString("SchoolAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sea Code.
        /// </summary>
        public static string SeaCode {
            get {
                return ResourceManager.GetString("SeaCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sequence Number.
        /// </summary>
        public static string SequenceNumber {
            get {
                return ResourceManager.GetString("SequenceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 7/8 (2) brails.
        /// </summary>
        public static string SevenEighthsBrailCount {
            get {
                return ResourceManager.GetString("SevenEighthsBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex Code (M/F/I/U).
        /// </summary>
        public static string SexCode {
            get {
                return ResourceManager.GetString("SexCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Adults.
        /// </summary>
        public static string SightingAdultCount {
            get {
                return ResourceManager.GetString("SightingAdultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Sighted.
        /// </summary>
        public static string SightingCount {
            get {
                return ResourceManager.GetString("SightingCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distance from Vessel.
        /// </summary>
        public static string SightingDistance {
            get {
                return ResourceManager.GetString("SightingDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Juveniles.
        /// </summary>
        public static string SightingJuvenileCount {
            get {
                return ResourceManager.GetString("SightingJuvenileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Estimate of Overall Length.
        /// </summary>
        public static string SightingLength {
            get {
                return ResourceManager.GetString("SightingLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiff Make.
        /// </summary>
        public static string SkiffMake {
            get {
                return ResourceManager.GetString("SkiffMake", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skiff Power.
        /// </summary>
        public static string SkiffPower {
            get {
                return ResourceManager.GetString("SkiffPower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Identifier.
        /// </summary>
        public static string SourceId {
            get {
                return ResourceManager.GetString("SourceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Name.
        /// </summary>
        public static string SourceName {
            get {
                return ResourceManager.GetString("SourceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Code.
        /// </summary>
        public static string SpeciesCode {
            get {
                return ResourceManager.GetString("SpeciesCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Species Description.
        /// </summary>
        public static string SpeciesDescription {
            get {
                return ResourceManager.GetString("SpeciesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speed.
        /// </summary>
        public static string Speed {
            get {
                return ResourceManager.GetString("Speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Speed Boats.
        /// </summary>
        public static string SpeedboatCount {
            get {
                return ResourceManager.GetString("SpeedboatCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Code.
        /// </summary>
        public static string StaffCode {
            get {
                return ResourceManager.GetString("StaffCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import Status.
        /// </summary>
        public static string StatusCode {
            get {
                return ResourceManager.GetString("StatusCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sum of all brails.
        /// </summary>
        public static string SumOfAllBrails {
            get {
                return ResourceManager.GetString("SumOfAllBrails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Number.
        /// </summary>
        public static string TagNumber {
            get {
                return ResourceManager.GetString("TagNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Organization.
        /// </summary>
        public static string TagOrg {
            get {
                return ResourceManager.GetString("TagOrg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag Type.
        /// </summary>
        public static string TagType {
            get {
                return ResourceManager.GetString("TagType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 3/4 (3) brails.
        /// </summary>
        public static string ThreeQuartersBrailCount {
            get {
                return ResourceManager.GetString("ThreeQuartersBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons of Bigeye.
        /// </summary>
        public static string TonsOfBigeye {
            get {
                return ResourceManager.GetString("TonsOfBigeye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons of Mixed Fish.
        /// </summary>
        public static string TonsOfMixed {
            get {
                return ResourceManager.GetString("TonsOfMixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons of Skipjack.
        /// </summary>
        public static string TonsOfSkipjack {
            get {
                return ResourceManager.GetString("TonsOfSkipjack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tons of Yellowfin.
        /// </summary>
        public static string TonsOfYellowfin {
            get {
                return ResourceManager.GetString("TonsOfYellowfin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total brails.
        /// </summary>
        public static string TotalBrailCount {
            get {
                return ResourceManager.GetString("TotalBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip Number.
        /// </summary>
        public static string TripNumber {
            get {
                return ResourceManager.GetString("TripNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of 2/3 (4) brails.
        /// </summary>
        public static string TwoThirdsBrailCount {
            get {
                return ResourceManager.GetString("TwoThirdsBrailCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated By.
        /// </summary>
        public static string UpdatedBy {
            get {
                return ResourceManager.GetString("UpdatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Updated Date.
        /// </summary>
        public static string UpdatedDate {
            get {
                return ResourceManager.GetString("UpdatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Departure Date (UTC).
        /// </summary>
        public static string UtcDepartureDate {
            get {
                return ResourceManager.GetString("UtcDepartureDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UTC Time.
        /// </summary>
        public static string UtcTime {
            get {
                return ResourceManager.GetString("UtcTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified By.
        /// </summary>
        public static string VerifiedBy {
            get {
                return ResourceManager.GetString("VerifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Date.
        /// </summary>
        public static string VerifiedDate {
            get {
                return ResourceManager.GetString("VerifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Registration Country (Flag).
        /// </summary>
        public static string VesselFlag {
            get {
                return ResourceManager.GetString("VesselFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Name.
        /// </summary>
        public static string VesselName {
            get {
                return ResourceManager.GetString("VesselName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Owner.
        /// </summary>
        public static string VesselOwner {
            get {
                return ResourceManager.GetString("VesselOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Type.
        /// </summary>
        public static string VesselType {
            get {
                return ResourceManager.GetString("VesselType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vessel Type Code.
        /// </summary>
        public static string VesselTypeCode {
            get {
                return ResourceManager.GetString("VesselTypeCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCPFC Number.
        /// </summary>
        public static string WcpfcNumber {
            get {
                return ResourceManager.GetString("WcpfcNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Capacity.
        /// </summary>
        public static string WellCapacity {
            get {
                return ResourceManager.GetString("WellCapacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Location.
        /// </summary>
        public static string WellLocation {
            get {
                return ResourceManager.GetString("WellLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well Number.
        /// </summary>
        public static string WellNumber {
            get {
                return ResourceManager.GetString("WellNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Direction.
        /// </summary>
        public static string WindDirection {
            get {
                return ResourceManager.GetString("WindDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wind Speed.
        /// </summary>
        public static string WindSpeed {
            get {
                return ResourceManager.GetString("WindSpeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year Built.
        /// </summary>
        public static string YearBuilt {
            get {
                return ResourceManager.GetString("YearBuilt", resourceCulture);
            }
        }
    }
}
